//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebService.CustomerServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        private int gradeField;
        
        private int SalesmanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int grade {
            get {
                return this.gradeField;
            }
            set {
                if ((this.gradeField.Equals(value) != true)) {
                    this.gradeField = value;
                    this.RaisePropertyChanged("grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference1.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name newCustomer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewCustomer", ReplyAction="*")]
        InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse InsertNewCustomer(InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse> InsertNewCustomerAsync(InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name newCustomer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerInfo", ReplyAction="*")]
        InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse UpdateCustomerInfo(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse> UpdateCustomerInfoAsync(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewCustomer", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequestBody Body;
        
        public InsertNewCustomerRequest() {
        }
        
        public InsertNewCustomerRequest(InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer;
        
        public InsertNewCustomerRequestBody() {
        }
        
        public InsertNewCustomerRequestBody(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            this.newCustomer = newCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponseBody Body;
        
        public InsertNewCustomerResponse() {
        }
        
        public InsertNewCustomerResponse(InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertNewCustomerResult;
        
        public InsertNewCustomerResponseBody() {
        }
        
        public InsertNewCustomerResponseBody(int InsertNewCustomerResult) {
            this.InsertNewCustomerResult = InsertNewCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerInfo", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequestBody Body;
        
        public UpdateCustomerInfoRequest() {
        }
        
        public UpdateCustomerInfoRequest(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer;
        
        public UpdateCustomerInfoRequestBody() {
        }
        
        public UpdateCustomerInfoRequestBody(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            this.newCustomer = newCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponseBody Body;
        
        public UpdateCustomerInfoResponse() {
        }
        
        public UpdateCustomerInfoResponse(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCustomerInfoResult;
        
        public UpdateCustomerInfoResponseBody() {
        }
        
        public UpdateCustomerInfoResponseBody(int UpdateCustomerInfoResult) {
            this.UpdateCustomerInfoResult = UpdateCustomerInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap>, InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap.InsertNewCustomer(InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest request) {
            return base.Channel.InsertNewCustomer(request);
        }
        
        public int InsertNewCustomer(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest inValue = new InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest();
            inValue.Body = new InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequestBody();
            inValue.Body.newCustomer = newCustomer;
            InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse retVal = ((InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap)(this)).InsertNewCustomer(inValue);
            return retVal.Body.InsertNewCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse> InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap.InsertNewCustomerAsync(InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest request) {
            return base.Channel.InsertNewCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.InsertNewCustomerResponse> InsertNewCustomerAsync(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest inValue = new InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequest();
            inValue.Body = new InventoryWebService.CustomerServiceReference1.InsertNewCustomerRequestBody();
            inValue.Body.newCustomer = newCustomer;
            return ((InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap)(this)).InsertNewCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap.UpdateCustomerInfo(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest request) {
            return base.Channel.UpdateCustomerInfo(request);
        }
        
        public int UpdateCustomerInfo(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest inValue = new InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest();
            inValue.Body = new InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequestBody();
            inValue.Body.newCustomer = newCustomer;
            InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse retVal = ((InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap)(this)).UpdateCustomerInfo(inValue);
            return retVal.Body.UpdateCustomerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse> InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap.UpdateCustomerInfoAsync(InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest request) {
            return base.Channel.UpdateCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoResponse> UpdateCustomerInfoAsync(InventoryWebService.CustomerServiceReference1.CustomerBO newCustomer) {
            InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest inValue = new InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequest();
            inValue.Body = new InventoryWebService.CustomerServiceReference1.UpdateCustomerInfoRequestBody();
            inValue.Body.newCustomer = newCustomer;
            return ((InventoryWebService.CustomerServiceReference1.CustomerWebServiceSoap)(this)).UpdateCustomerInfoAsync(inValue);
        }
    }
}
