//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebService.SalesmanServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesmanBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SalesmanBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SalesmanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        private float CommissionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Commission {
            get {
                return this.CommissionField;
            }
            set {
                if ((this.CommissionField.Equals(value) != true)) {
                    this.CommissionField = value;
                    this.RaisePropertyChanged("Commission");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesmanServiceReference1.SalesmanWebServiceSoap")]
    public interface SalesmanWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name newSalesman from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewSalesman", ReplyAction="*")]
        InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse InsertNewSalesman(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewSalesman", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse> InsertNewSalesmanAsync(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest request);
        
        // CODEGEN: Generating message contract since element name newSalesman from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSalesmanInfo", ReplyAction="*")]
        InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse UpdateSalesmanInfo(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSalesmanInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse> UpdateSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest request);
        
        // CODEGEN: Generating message contract since element name newSalesman from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSalesmanInfo", ReplyAction="*")]
        InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse DeleteSalesmanInfo(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSalesmanInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse> DeleteSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewSalesmanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewSalesman", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequestBody Body;
        
        public InsertNewSalesmanRequest() {
        }
        
        public InsertNewSalesmanRequest(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewSalesmanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman;
        
        public InsertNewSalesmanRequestBody() {
        }
        
        public InsertNewSalesmanRequestBody(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            this.newSalesman = newSalesman;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewSalesmanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewSalesmanResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponseBody Body;
        
        public InsertNewSalesmanResponse() {
        }
        
        public InsertNewSalesmanResponse(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewSalesmanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertNewSalesmanResult;
        
        public InsertNewSalesmanResponseBody() {
        }
        
        public InsertNewSalesmanResponseBody(int InsertNewSalesmanResult) {
            this.InsertNewSalesmanResult = InsertNewSalesmanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSalesmanInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSalesmanInfo", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequestBody Body;
        
        public UpdateSalesmanInfoRequest() {
        }
        
        public UpdateSalesmanInfoRequest(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSalesmanInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman;
        
        public UpdateSalesmanInfoRequestBody() {
        }
        
        public UpdateSalesmanInfoRequestBody(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            this.newSalesman = newSalesman;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSalesmanInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSalesmanInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponseBody Body;
        
        public UpdateSalesmanInfoResponse() {
        }
        
        public UpdateSalesmanInfoResponse(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSalesmanInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateSalesmanInfoResult;
        
        public UpdateSalesmanInfoResponseBody() {
        }
        
        public UpdateSalesmanInfoResponseBody(int UpdateSalesmanInfoResult) {
            this.UpdateSalesmanInfoResult = UpdateSalesmanInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSalesmanInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSalesmanInfo", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequestBody Body;
        
        public DeleteSalesmanInfoRequest() {
        }
        
        public DeleteSalesmanInfoRequest(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSalesmanInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman;
        
        public DeleteSalesmanInfoRequestBody() {
        }
        
        public DeleteSalesmanInfoRequestBody(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            this.newSalesman = newSalesman;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSalesmanInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSalesmanInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponseBody Body;
        
        public DeleteSalesmanInfoResponse() {
        }
        
        public DeleteSalesmanInfoResponse(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSalesmanInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteSalesmanInfoResult;
        
        public DeleteSalesmanInfoResponseBody() {
        }
        
        public DeleteSalesmanInfoResponseBody(int DeleteSalesmanInfoResult) {
            this.DeleteSalesmanInfoResult = DeleteSalesmanInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesmanWebServiceSoapChannel : InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesmanWebServiceSoapClient : System.ServiceModel.ClientBase<InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap>, InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap {
        
        public SalesmanWebServiceSoapClient() {
        }
        
        public SalesmanWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesmanWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesmanWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesmanWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.InsertNewSalesman(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest request) {
            return base.Channel.InsertNewSalesman(request);
        }
        
        public int InsertNewSalesman(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest inValue = new InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequestBody();
            inValue.Body.newSalesman = newSalesman;
            InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse retVal = ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).InsertNewSalesman(inValue);
            return retVal.Body.InsertNewSalesmanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse> InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.InsertNewSalesmanAsync(InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest request) {
            return base.Channel.InsertNewSalesmanAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanResponse> InsertNewSalesmanAsync(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest inValue = new InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.InsertNewSalesmanRequestBody();
            inValue.Body.newSalesman = newSalesman;
            return ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).InsertNewSalesmanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.UpdateSalesmanInfo(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest request) {
            return base.Channel.UpdateSalesmanInfo(request);
        }
        
        public int UpdateSalesmanInfo(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest inValue = new InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequestBody();
            inValue.Body.newSalesman = newSalesman;
            InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse retVal = ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).UpdateSalesmanInfo(inValue);
            return retVal.Body.UpdateSalesmanInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse> InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.UpdateSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest request) {
            return base.Channel.UpdateSalesmanInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoResponse> UpdateSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest inValue = new InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.UpdateSalesmanInfoRequestBody();
            inValue.Body.newSalesman = newSalesman;
            return ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).UpdateSalesmanInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.DeleteSalesmanInfo(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest request) {
            return base.Channel.DeleteSalesmanInfo(request);
        }
        
        public int DeleteSalesmanInfo(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest inValue = new InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequestBody();
            inValue.Body.newSalesman = newSalesman;
            InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse retVal = ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).DeleteSalesmanInfo(inValue);
            return retVal.Body.DeleteSalesmanInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse> InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap.DeleteSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest request) {
            return base.Channel.DeleteSalesmanInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoResponse> DeleteSalesmanInfoAsync(InventoryWebService.SalesmanServiceReference1.SalesmanBO newSalesman) {
            InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest inValue = new InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequest();
            inValue.Body = new InventoryWebService.SalesmanServiceReference1.DeleteSalesmanInfoRequestBody();
            inValue.Body.newSalesman = newSalesman;
            return ((InventoryWebService.SalesmanServiceReference1.SalesmanWebServiceSoap)(this)).DeleteSalesmanInfoAsync(inValue);
        }
    }
}
