//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebService.OrderServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdersBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrdersBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderNoField;
        
        private float PurchAmtField;
        
        private System.DateTime OrderDateField;
        
        private int CustomerIdField;
        
        private int SalesmanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((this.OrderNoField.Equals(value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float PurchAmt {
            get {
                return this.PurchAmtField;
            }
            set {
                if ((this.PurchAmtField.Equals(value) != true)) {
                    this.PurchAmtField = value;
                    this.RaisePropertyChanged("PurchAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference1.OrdersWebServiceSoap")]
    public interface OrdersWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name newOrder from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewOrder", ReplyAction="*")]
        InventoryWebService.OrderServiceReference1.InsertNewOrderResponse InsertNewOrder(InventoryWebService.OrderServiceReference1.InsertNewOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.InsertNewOrderResponse> InsertNewOrderAsync(InventoryWebService.OrderServiceReference1.InsertNewOrderRequest request);
        
        // CODEGEN: Generating message contract since element name newOrder from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrdersInfo", ReplyAction="*")]
        InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse UpdateOrdersInfo(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrdersInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse> UpdateOrdersInfoAsync(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest request);
        
        // CODEGEN: Generating message contract since element name newOrder from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrdersInfo", ReplyAction="*")]
        InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse DeleteOrdersInfo(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrdersInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse> DeleteOrdersInfoAsync(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewOrder", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.InsertNewOrderRequestBody Body;
        
        public InsertNewOrderRequest() {
        }
        
        public InsertNewOrderRequest(InventoryWebService.OrderServiceReference1.InsertNewOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.OrderServiceReference1.OrdersBO newOrder;
        
        public InsertNewOrderRequestBody() {
        }
        
        public InsertNewOrderRequestBody(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            this.newOrder = newOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.InsertNewOrderResponseBody Body;
        
        public InsertNewOrderResponse() {
        }
        
        public InsertNewOrderResponse(InventoryWebService.OrderServiceReference1.InsertNewOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertNewOrderResult;
        
        public InsertNewOrderResponseBody() {
        }
        
        public InsertNewOrderResponseBody(int InsertNewOrderResult) {
            this.InsertNewOrderResult = InsertNewOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrdersInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrdersInfo", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequestBody Body;
        
        public UpdateOrdersInfoRequest() {
        }
        
        public UpdateOrdersInfoRequest(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrdersInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.OrderServiceReference1.OrdersBO newOrder;
        
        public UpdateOrdersInfoRequestBody() {
        }
        
        public UpdateOrdersInfoRequestBody(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            this.newOrder = newOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrdersInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrdersInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponseBody Body;
        
        public UpdateOrdersInfoResponse() {
        }
        
        public UpdateOrdersInfoResponse(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrdersInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateOrdersInfoResult;
        
        public UpdateOrdersInfoResponseBody() {
        }
        
        public UpdateOrdersInfoResponseBody(int UpdateOrdersInfoResult) {
            this.UpdateOrdersInfoResult = UpdateOrdersInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrdersInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrdersInfo", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequestBody Body;
        
        public DeleteOrdersInfoRequest() {
        }
        
        public DeleteOrdersInfoRequest(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrdersInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InventoryWebService.OrderServiceReference1.OrdersBO newOrder;
        
        public DeleteOrdersInfoRequestBody() {
        }
        
        public DeleteOrdersInfoRequestBody(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            this.newOrder = newOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrdersInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrdersInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponseBody Body;
        
        public DeleteOrdersInfoResponse() {
        }
        
        public DeleteOrdersInfoResponse(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrdersInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteOrdersInfoResult;
        
        public DeleteOrdersInfoResponseBody() {
        }
        
        public DeleteOrdersInfoResponseBody(int DeleteOrdersInfoResult) {
            this.DeleteOrdersInfoResult = DeleteOrdersInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersWebServiceSoapChannel : InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersWebServiceSoapClient : System.ServiceModel.ClientBase<InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap>, InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap {
        
        public OrdersWebServiceSoapClient() {
        }
        
        public OrdersWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.OrderServiceReference1.InsertNewOrderResponse InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.InsertNewOrder(InventoryWebService.OrderServiceReference1.InsertNewOrderRequest request) {
            return base.Channel.InsertNewOrder(request);
        }
        
        public int InsertNewOrder(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.InsertNewOrderRequest inValue = new InventoryWebService.OrderServiceReference1.InsertNewOrderRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.InsertNewOrderRequestBody();
            inValue.Body.newOrder = newOrder;
            InventoryWebService.OrderServiceReference1.InsertNewOrderResponse retVal = ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).InsertNewOrder(inValue);
            return retVal.Body.InsertNewOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.InsertNewOrderResponse> InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.InsertNewOrderAsync(InventoryWebService.OrderServiceReference1.InsertNewOrderRequest request) {
            return base.Channel.InsertNewOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.InsertNewOrderResponse> InsertNewOrderAsync(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.InsertNewOrderRequest inValue = new InventoryWebService.OrderServiceReference1.InsertNewOrderRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.InsertNewOrderRequestBody();
            inValue.Body.newOrder = newOrder;
            return ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).InsertNewOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.UpdateOrdersInfo(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest request) {
            return base.Channel.UpdateOrdersInfo(request);
        }
        
        public int UpdateOrdersInfo(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest inValue = new InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequestBody();
            inValue.Body.newOrder = newOrder;
            InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse retVal = ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).UpdateOrdersInfo(inValue);
            return retVal.Body.UpdateOrdersInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse> InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.UpdateOrdersInfoAsync(InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest request) {
            return base.Channel.UpdateOrdersInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.UpdateOrdersInfoResponse> UpdateOrdersInfoAsync(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest inValue = new InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.UpdateOrdersInfoRequestBody();
            inValue.Body.newOrder = newOrder;
            return ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).UpdateOrdersInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.DeleteOrdersInfo(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest request) {
            return base.Channel.DeleteOrdersInfo(request);
        }
        
        public int DeleteOrdersInfo(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest inValue = new InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequestBody();
            inValue.Body.newOrder = newOrder;
            InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse retVal = ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).DeleteOrdersInfo(inValue);
            return retVal.Body.DeleteOrdersInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse> InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap.DeleteOrdersInfoAsync(InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest request) {
            return base.Channel.DeleteOrdersInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryWebService.OrderServiceReference1.DeleteOrdersInfoResponse> DeleteOrdersInfoAsync(InventoryWebService.OrderServiceReference1.OrdersBO newOrder) {
            InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest inValue = new InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequest();
            inValue.Body = new InventoryWebService.OrderServiceReference1.DeleteOrdersInfoRequestBody();
            inValue.Body.newOrder = newOrder;
            return ((InventoryWebService.OrderServiceReference1.OrdersWebServiceSoap)(this)).DeleteOrdersInfoAsync(inValue);
        }
    }
}
